=begin
JISORT API

This is a sample server Login server.  Sample api documentation for system login.The API login is the simplest method of integration for most applications. It will allow the user to provide their username and password.

OpenAPI spec version: 1.0.0
Contact: beatrice@jisort.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')

    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method

  end

  add_swagger_route 'GET', '/products/applied_loans/', controller_name: 'loan', action_name: 'login_user'
  add_swagger_route 'POST', '/messenger/outbox/', controller_name: 'messenger', action_name: 'messenger_outbox_post'
  add_swagger_route 'GET', '/messenger/outbox/?message_status', controller_name: 'messenger', action_name: 'messenger_outboxmessage_status_get'
  add_swagger_route 'POST', '/mpa/client_payments/', controller_name: 'mpa', action_name: 'mpa_client_payments_post'
  add_swagger_route 'GET', '/products/repayment_schedule/?loan', controller_name: 'product', action_name: 'login_user'
  add_swagger_route 'POST', '/products/loans/', controller_name: 'product', action_name: 'login_user_1'
  add_swagger_route 'POST', '/product/loan_charge/', controller_name: 'product', action_name: 'product_loan_charge_post'
  add_swagger_route 'PATCH', '/products/applied_loans/{id}/', controller_name: 'product', action_name: 'products_applied_loans_id_patch'
  add_swagger_route 'PATCH', '/products/applied_loans/{id}/&#39;', controller_name: 'product', action_name: 'products_applied_loans_id_patch_2'
  add_swagger_route 'POST', '/products/applied_loans/', controller_name: 'product', action_name: 'products_applied_loans_post'
  add_swagger_route 'POST', '/products/formulas/', controller_name: 'product', action_name: 'products_formulas_post'
  add_swagger_route 'POST', '/products/loan_disbursement/', controller_name: 'product', action_name: 'products_loan_disbursement_post'
  add_swagger_route 'POST', '/products/loan_guarantors/', controller_name: 'product', action_name: 'products_loan_guarantors_post'
  add_swagger_route 'POST', '/products/repayment_schedule/', controller_name: 'product', action_name: 'products_repayment_schedule_post'
  add_swagger_route 'POST', '/registration/collateral_registration/', controller_name: 'product', action_name: 'registration_collateral_registration_post'
  add_swagger_route 'POST', '/registration/next_of_kin/', controller_name: 'registration', action_name: 'create_next_of_kin'
  add_swagger_route 'POST', '/registration/agents/', controller_name: 'registration', action_name: 'registration_agents_post'
  add_swagger_route 'POST', '/registration/bank_branch/', controller_name: 'registration', action_name: 'registration_bank_branch_post'
  add_swagger_route 'POST', '/registration/banks/', controller_name: 'registration', action_name: 'registration_banks_post'
  add_swagger_route 'POST', '/registration/chart_accounts/', controller_name: 'registration', action_name: 'registration_chart_accounts_post'
  add_swagger_route 'POST', '/registration/currency/', controller_name: 'registration', action_name: 'registration_currency_post'
  add_swagger_route 'POST', '/registration/group_registration/', controller_name: 'registration', action_name: 'registration_group_registration_post'
  add_swagger_route 'GET', '/registration/member_accounts/{id}/', controller_name: 'registration', action_name: 'registration_member_accounts_id_get'
  add_swagger_route 'POST', '/registration/member_accounts/', controller_name: 'registration', action_name: 'registration_member_accounts_post'
  add_swagger_route 'POST', '/registration/member_bank/', controller_name: 'registration', action_name: 'registration_member_bank_post'
  add_swagger_route 'POST', '/registration/member_group/', controller_name: 'registration', action_name: 'registration_member_group_post'
  add_swagger_route 'POST', '/registration/member_uploads/', controller_name: 'registration', action_name: 'registration_member_uploads_post'
  add_swagger_route 'POST', '/registration/members/', controller_name: 'registration', action_name: 'registration_members_post'
  add_swagger_route 'GET', '/registration/non_member_registration/{id}', controller_name: 'registration', action_name: 'registration_non_member_registration_id_get'
  add_swagger_route 'POST', '/registration/non_member_registration/', controller_name: 'registration', action_name: 'registration_non_member_registration_post'
  add_swagger_route 'POST', '/registration/payment_modes/', controller_name: 'registration', action_name: 'registration_payment_modes_post'
  add_swagger_route 'POST', '/registration/social_economics/', controller_name: 'registration', action_name: 'registration_social_economics_post'
  add_swagger_route 'POST', '/registration/work_details/', controller_name: 'registration', action_name: 'registration_work_details_post'
  add_swagger_route 'POST', '/registration/login/', controller_name: 'user', action_name: 'update_pet_with_form'
end
