=begin
JISORT API

This is a sample server Login server.  Sample api documentation for system login.The API login is the simplest method of integration for most applications. It will allow the user to provide their username and password.  

OpenAPI spec version: 1.0.0
Contact: beatrice@jisort.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ProductController < ApplicationController

  def login_user
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def login_user_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def product_loan_charge_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def products_applied_loans_id_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def products_applied_loans_id_patch_2
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def products_applied_loans_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def products_formulas_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def products_loan_disbursement_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def products_loan_guarantors_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def products_repayment_schedule_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_collateral_registration_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
