=begin
JISORT API

This is a sample server Login server.  Sample api documentation for system login.The API login is the simplest method of integration for most applications. It will allow the user to provide their username and password.  

OpenAPI spec version: 1.0.0
Contact: beatrice@jisort.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class RegistrationController < ApplicationController

  def create_next_of_kin
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_agents_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_bank_branch_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_banks_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_chart_accounts_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_currency_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_group_registration_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_member_accounts_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_member_accounts_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_member_bank_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_member_group_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_member_uploads_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_members_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_non_member_registration_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_non_member_registration_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_payment_modes_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_social_economics_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def registration_work_details_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
